import sys
Import('check_env')

env = check_env.Clone()

env.Prepend(LIBS=File('#/galerautils/src/galerautils.lib'))
env.Prepend(LIBS=File('#/galerautils/src/galerautils++.lib'))
env.Prepend(LIBS=File('#/gcache/src/gcache.lib'))

source = Glob('*.cpp')
if sys.platform.find("win")==0:
    gcache_tests = env.Program(target = 'gcache_tests.exe', source = source)
else:
    gcache_tests = env.Program(target = 'gcache_tests', source = source)

#                           source = Split('''
#                                 gcache_tests.cpp
#                           '''))

stamp="gcache_tests.passed"
env.Test(stamp, gcache_tests)
env.Alias("test", stamp)

Clean(gcache_tests, ['#/gcache_tests.log', '#/gcache.page.000000', '#/rb_test'])
