import sys
Import('check_env')

env = check_env.Clone()
if sys.platform.find("win")==0:
	target='gcache_tests.exe'
	env.Prepend(LIBS=File('galerautils/src/galerautils.lib'))
	env.Prepend(LIBS=File('galerautils/src/galerautils++.lib'))
	env.Prepend(LIBS=File('gcache/src/gcache.lib'))
else:
	target='gcache_tests'
	env.Prepend(LIBS=File('#/galerautils/src/libgalerautils.a'))
	env.Prepend(LIBS=File('#/galerautils/src/libgalerautils++.a'))
	env.Prepend(LIBS=File('#/gcache/src/libgcache.a'))
source = Glob('*.cpp')
gcache_tests = env.Program(target = target, source = source)

#                           source = Split('''
#                                 gcache_tests.cpp
#                           '''))

stamp="gcache_tests.passed"
env.Test(stamp, gcache_tests)
env.Alias("test", stamp)

Clean(gcache_tests, ['#/gcache_tests.log', '#/gcache.page.000000', '#/rb_test'])
