import sys
Import('check_env')

env = check_env.Clone()
if sys.platform.find("win") != 0:
    env.Prepend(LIBS=File('#/galerautils/src/libgalerautils.a'))
    env.Prepend(LIBS=File('#/galerautils/src/libgalerautils++.a'))
    env.Prepend(LIBS=File('#/gcomm/src/libgcomm.a'))
else:
    env.Prepend(LIBS=File('#/galerautils/src/galerautils.lib'))
    env.Prepend(LIBS=File('#/galerautils/src/galerautils++.lib'))
    env.Prepend(LIBS=File('#/gcomm/src/gcomm.lib'))
gcomm_check = env.Program(target = 'check_gcomm',
                          source = Split('''
                              check_gcomm.cpp
                              check_trace.cpp
                              check_types.cpp
                              check_util.cpp
                              check_gmcast.cpp
                              check_evs2.cpp
                              check_pc.cpp
                           '''))

if 1 == 0:
    env.Test("gcomm_check.passed", gcomm_check)

Clean(gcomm_check, '#/check_gcomm.log')


ssl_test = env.Program(target = 'ssl_test',
                       source = ['ssl_test.cpp'])
