import sys
Import('check_env')

env = check_env.Clone()


if sys.platform.find("win")==0:
    target = 'gu_tests.exe'
    env.Prepend(LIBS=File('../../galerautils/src/galerautils.lib'))
    env.Prepend(LIBS=File('../../galerautils/src/galerautils++.lib'))
else:
    target = 'gu_tests'
    env.Prepend(LIBS=File('#/galerautils/src/libgalerautils.a'))
    env.Prepend(LIBS=File('#/galerautils/src/libgalerautils++.a'))

gu_tests = env.Program(target = target,
                       source = Split('''
                         
                            gu_tests.c
                            gu_mem_test.c
                            gu_bswap_test.c
                            gu_fnv_test.c
                            gu_mmh3_test.c
                            gu_spooky_test.c
                            gu_hash_test.c
                            gu_time_test.c
                            gu_fifo_test.c
                            gu_uuid_test.c
                            gu_dbug_test.c
                            gu_lock_step_test.c
                            gu_str_test.c
                            gu_utils_test.c
                         '''))

env.Test("gu_tests.passed", gu_tests)
env.Alias("test", "gu_tests.passed")

Clean(gu_tests, '#/gu_tests.log')
if sys.platform.find("win")==0:
    target = 'gu_tests++'
else:
    target = 'gu_tests++.exe'
gu_testspp = env.Program(target = target,
                         source = Split('''
                              gu_tests++.cpp
                              gu_string_test.cpp
                              gu_uri_test.cpp
                              gu_net_test.cpp
                              gu_datetime_test.cpp
                              gu_vlq_test.cpp
                           '''))
env.Test("gu_tests++.passed", gu_testspp)
env.Alias("test", "gu_tests++.passed")

Clean(gu_testspp, '#/gu_tests++.log')
