
Import('check_env')

env = check_env.Clone()
env.Append(LIBS=File('#/gcache/src/gcache.lib'))
env.Append(LIBS=File('#/galera/src/galera++.lib'))
env.Append(LIBS=File('#/galerautils/src/galerautils++.lib'))
env.Append(LIBS=File('#/galerautils/src/galerautils.lib'))
#env.Append(LIBS = ['pthread',
#                   'rt'])

galera_check = env.Program(target='galera_check',
                           source=Split('''
                               galera_check.cpp
                               write_set_check.cpp
                               trx_handle_check.cpp
                               service_thd_check.cpp
                               ist_check.cpp
                               saved_state_check.cpp
                           '''))

stamp = "galera_check.passed"
if 1 == 0:
    env.Test(stamp, galera_check)
env.Alias("test", stamp)

Clean(galera_check, ['#/galera_check.log', 'ist_check.cache'])
